export default {
    THEME_INIT: 'THEME_INIT',
    THEME_CHANGE: 'THEME_CHANGE',
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
    POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
    POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
    POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
}